### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by darrylb123** [thmahe/usbrelay-firmware#2]
Trying to build the code following your doco.
xx@xx:/var/tmp$ git clone git@github.com:thmahe/usbrelay-firmware.git
Cloning into 'usbrelay-firmware'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 26 (delta 6), reused 19 (delta 2), pack-reused 0
Receiving objects: 100% (26/26), 83.56 KiB | 154.00 KiB/s, done.
Resolving deltas: 100% (6/6), done.
xx@xx:/var/tmp$ cd usbrelay-firmware
xx@xx:/var/tmp/usbrelay-firmware$ ls
circuit  LICENSE  Makefile  README.md  src  submodules
xx@xx:/var/tmp/usbrelay-firmware$ make firmware
make: *** No rule to make target 'build/obj/usbdrv.o', needed by 'firmware'.  Stop.

I believe it is missing the v-usb code in submodules

**Comment by darrylb123** [comment]
What serial device do you use when the device is a HID device?

**Comment by thmahe** [comment]
Hi @darrylb123,

You were right, I've missed the submodules init/update instructions in readme. **Fixed with above commit.**

> What serial device do you use when the device is a HID device?
I do not understand your question, this firmware does not rely on serial communication at all. 
Control of dcttech.com boards & design included in this repository is purely done through v-sub stack. 

If your question is related to USB vid:pid, you must refer to https://www.obdev.at/products/vusb/license.html

**Comment by darrylb123** [comment]
Sorry I wasn't clear. My question should have been:
What serial device should I use to program the new firmware when it comes
up as a hid device by default?

**Comment by thmahe** [comment]
You can use a dedicated AVR programmer or a sidekick microcontroller following method below:
[arduino.cc - Arduino as ISP and Arduino Bootloaders](https://docs.arduino.cc/built-in-examples/arduino-isp/ArduinoISP/)

From my end I was using a cheap [Arduino Nano](https://docs.arduino.cc/hardware/nano/) to burn the firmware.

**Programming pads on dcttech.com device**
![image](https://github.com/user-attachments/assets/678ac5fe-92f2-4fc1-8907-616305615b1a)

Strongly recommend to solder a 4 pin header on above pads, with as next step identification of pins (MOSI, MISO, CSK & Reset) in order to program the micro-controller. 

**dcttech.com boards must be powered through USB during burn**
